<?php
/**
 * @file
 * Core functionality for Admin Select module.
 */

/**
 * Include additional files.
 */
foreach (module_list() as $module) {
  if (file_exists($file = dirname(__FILE__) . "/includes/{$module}.inc")) {
    require_once $file;
  }
}

/**
 * Imeplements hook_user().
 */
function admin_select_user($op, &$edit, &$account, $category = NUL) {
  if ($op == 'form' && $category == 'account') {
    $admin_modules = module_invoke_all('admin_select_module');
    if (count($admin_modules) > 1) {
      $data = unserialize($edit['data']);
      $form = array();

      $form['admin_select'] = array(
        '#type' => 'fieldset',
        '#title' => t('Admin Select settings'),
        '#collapsible' => TRUE,
      );
      $form['admin_select']['admin_select'] = array(
        '#type' => 'select',
        '#options' => $admin_modules,
        '#default_value' => isset($data['admin_select']) ? $data['admin_select'] : current(array_keys($admin_modules)),
      );

      return $form;
    }
  }
}
