<?php
/**
 * @file
 * Core functionality for Admin Select module.
 */

/**
 * Implements hook_init().
 */
function admin_select_init() {
  global $user;
  $data = unserialize($user->data);
  $data['admin_select'] = isset($data['admin_select']) ? $data['admin_select'] : 'admin';
  switch($data['admin_select']) {
    case 'admin':
      admin_menu_suppress();
      break;
    case 'admin_menu':
      admin_suppress();
      break;
  }
}

/**
 * Imeplements hook_user().
 */
function admin_select_user($op, &$edit, &$account, $category = NUL) {
  if ($op == 'form' && $category == 'account') {
    $data = unserialize($edit['data']);
    $form = array();

    $form['admin_select'] = array(
      '#type' => 'fieldset',
      '#title' => t('Admin Select settings'),
      '#collapsible' => TRUE,
    );
    $form['admin_select']['admin_select'] = array(
      '#type' => 'select',
      '#options' => array(
        'admin' => t('Admin module'),
        'admin_menu' => t('Admin Menu module'),
       ),
      '#default_value' => isset($data['admin_select']) ? $data['admin_select'] : 'admin',
    );

    return $form;
  }
}
